In [62]:
import torch

torch.cuda.is_available()

True

# Initialization

In [63]:
x = torch.tensor([[1, 2], [3, 4]])
x

tensor([[1, 2],
        [3, 4]])

In [64]:
x_ones = torch.ones_like(x)
print(x_ones)
x_ones = torch.ones(x.shape)
print(x_ones)
x_zero = torch.zeros(x.shape, dtype=torch.float)
print(x_zero)
x_rand = torch.rand_like(x, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3824, 0.2910],
        [0.1449, 0.4841]])


## Properties

In [65]:
print(f"Shape of tensor: {x.shape}")
print(f"Datatype of tensor: {x.dtype}")
print(f"Datatype of tensor: {x_zero.dtype}")
print(f"Device tensor is stored on: {x.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Send to device

In [66]:
x = x.to("cuda")
x

tensor([[1, 2],
        [3, 4]], device='cuda:0')

# Working with tensors
## Indexing & Slicing

In [67]:
tensor = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [68]:
print(f"First row:\n{tensor[0]}\n")
first_col = tensor[:,0]
print(f"First col:\n{first_col}\n")
second_and_third_col = tensor[:, 1:3]
print(f"Second + third col:\n{second_and_third_col}\n")

First row:
tensor([1, 2, 3, 4])

First col:
tensor([ 1,  5,  9, 13])

Second + third col:
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])



In [82]:
# Expand by one dimension & transpose (col)
first_col_2d = first_col.expand([1, 4]).transpose(0, 1)
print(first_col_2d)
# Re-construct cols 1-3
res = torch.cat([first_col_2d, second_and_third_col], dim=1)
print(res)
# Add first column as row below. First reduce to 3 elements & transpose the column to get a row
to_add = first_col_2d[0:3,:].transpose(0, 1)
print(to_add)
res = torch.cat([res, to_add], dim=0)
print(res)

tensor([[ 1],
        [ 5],
        [ 9],
        [13]])
tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])
tensor([[1, 5, 9]])
tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15],
        [ 1,  5,  9]])


## Arithmetic
### Matrix multiplication

In [89]:
a = torch.tensor([[1, 2, 3], [2, 3, 4]])
b = torch.tensor([[5, 6], [7,8], [9,0]])
print(a)
print(b)
print()
print(a@b)
print(a.matmul(b))

tensor([[1, 2, 3],
        [2, 3, 4]])
tensor([[5, 6],
        [7, 8],
        [9, 0]])

tensor([[46, 22],
        [67, 36]])
tensor([[46, 22],
        [67, 36]])


## Element-wise operations

In [96]:
a = torch.tensor([[1, 2, 3], [2, 3, 4]])
b = torch.tensor([[5, 6, 7], [8, 9, 0]])
print(a*b)
print(a.mul(b))
print()

result_tensor = torch.zeros(a.shape)
torch.mul(a, b, out=result_tensor)
print(result_tensor)

tensor([[ 5, 12, 21],
        [16, 27,  0]])
tensor([[ 5, 12, 21],
        [16, 27,  0]])

tensor([[ 5., 12., 21.],
        [16., 27.,  0.]])


In [101]:
print(result_tensor.sum())

single_element = torch.tensor(5)
print(single_element.sum())
print(single_element.item())

print(single_element.add_(5))

tensor(81.)
tensor(5)
5
tensor(10)
